<?php
/**
 * PagSeguro Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   design
 * @package    BrunoAssarisse_PagSeguro
 * @copyright  Copyright (c) 2010 Bruno Assarisse (www.assarisse.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Bruno Assarisse <bruno@assarisse.com.br>
 */
		
?>
    <p>
        <strong><?php echo $this->getMethod()->getTitle() ?></strong>
        
        <?php if ($this->getShowPaylink()): ?>
        (<a href="<?php echo $this->getPayUrl(); ?>" onclick="this.target='_blank'">pagar</a>)
        <?php endif; ?>

        <?php if ($this->getShowInfo()): ?>
        <br />ID da transação: <?php echo $this->getTransactionId(); ?>
        <br />Forma de pagamento: <?php echo $this->getPaymentMethod(); ?>
        <?php endif; ?>

    </p>